version: '3'

services:
   traefik:
    image: traefik:v2.1
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/dinamic:/etc/traefik
      - ./data/acme.json:/acme.json
      - ../../ssl:/etc/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:${PASSWORD_TRAEFIK}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik-secure.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.traefik-secure.loadbalancer.sticky.cookie.name=ckn"
      - "traefik.http.services.traefik-secure.loadbalancer.sticky.cookie.secure=true"
   

networks:
  proxy:
    external: true
